name: Sync SCSS to READMEs

on:
  push:
    branches: [ "master" ]
    paths: 
      - "themes/maple-neon.scss"
      - "docs/README.*.md"
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC

jobs:
  sync-scss:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update READMEs with latest SCSS
        run: |
          # Escape SCSS content for sed
          SCSS_CONTENT=$(sed -e ':a' -e 'N' -e '$!ba' -e 's/[\/&]/\\&/g' -e 's/\n/\\n/g' themes/maple-neon.scss)
          
          # Update all README files between the scss code markers
          for file in README.md docs/README.*.md; do
            sed -i "/^```scss$/,/^```$/c\`\`\`scss\n$SCSS_CONTENT\n\`\`\`" "$file"
          done

      - name: Commit changes if modified
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            # Reset to origin/master to ensure clean state
            git fetch origin
            git reset --hard origin/master
            
            # Re-apply changes
            git add README.md docs/README.*.md
            git commit -m "docs: Update all READMEs with latest SCSS from maple-neon.scss"
            
            # Push with lease to prevent race conditions
            git push --force-with-lease "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master
          fi
